export const GET_SHOPPING_LIST_BEGIN = "GET_SHOPPING_LIST_BEGIN";
export const GET_SHOPPING_LIST_SUCCESS = "GET_SHOPPING_LIST_SUCCESS";
export const GET_SHOPPING_LIST_FAILURE = "GET_SHOPPING_LIST_FAILURE";

export const SORT_SHOPPING_LIST_DISCOUNT = "SORT_SHOPPING_LIST_DISCOUNT";
export const SORT_SHOPPING_LIST_HIGH_LOW = "SORT_SHOPPING_LIST_HIGH_LOW";
export const SORT_SHOPPING_LIST_LOW_HIGH = "SORT_SHOPPING_LIST_LOW_HIGH";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";

export const APPLY_FILTER = "APPLY_FILTER";